modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="kiza_base_mod"
version="1.3.4"
displayName="Kiza Client Runtime"
authors="Kiza Mods"
description='''
Kiza Launcher integration and local player-state bridge.
'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.kiza_base_mod]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="CLIENT"

[[dependencies.kiza_base_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.17,)"
ordering="NONE"
side="CLIENT"
